chore!: add exports map to @waku/utils
logos-messaging/logos-delivery-js pull request #1201
Opened 2023-02-26 19:06 UTC by danisharora099

ref: https://github.com/waku-org/js-waku/issues/1043, https://github.com/waku-org/js-waku/pull/1149#discussion_r1111449821

2023-02-26 22:35 UTC, fryorcraken requested changes

2023-02-26 22:35 UTC, fryorcraken commented on packages/utils/package.json
> +    "./libp2p": {
You need to update the rollup config file with the same path

2023-02-28 04:09 UTC, fryorcraken commented on packages/utils/package.json
> +    "./libp2p": {
You can discard this comment once https://github.com/waku-org/js-waku/pull/1204 is merged

2023-03-13 21:30 UTC, weboko approved these changes

2023-03-14 00:25 UTC, fryorcraken approved these changes

2023-03-14 04:40 UTC, merged