chore: remove prettier, and default to eslint
logos-messaging/logos-delivery-js pull request #1495
Opened 2023-08-22 06:02 UTC by danisharora099

This PR 
- removes prettier altogether
- uses eslint for formatting + linting
- sets vscode default formatter to eslint, from prettier
- reruns `npm run proto`
   - since we don't run `prettier` on it anymore, there is a huge diff
   - ideally, we should remove `proto` from `eslintIgnore` but i am not sure why it was added to ignore (https://github.com/waku-org/js-waku/commit/704f2770d1d4aac64726071bad2a22ef7aa84e66)

2023-08-22 11:24 UTC, fryorcraken requested changes
Do not run format or lint on generated files:
- it just creates more mess as you know have 2 scripts that breaks each-other outputs (same as you had with eslint and prettier)
- the files are auto-generated so nobody is going to "mess up" the formatting
- the files are auto-generated so even if the linter find an issue, there is nothing you will be able to do to fix it.

2023-08-29 04:22 UTC, fryorcraken commented on .eslintrc.json
> -        "import/no-extraneous-dependencies": [
Why removing this?

2023-08-29 04:22 UTC, fryorcraken commented on .eslintrc.json
> -    "project": ["./tsconfig.json"]
Why removing this?

2023-08-31 16:27 UTC, weboko commented on .eslintrc.json
> +   "parserOptions": {
probably you need to re-run prettier/linter

2023-08-31 16:31 UTC, weboko commented on packages/proto/src/lib/filter.ts
> +          if ((obj.contentTopic != null && obj.contentTopic !== '')) {
oh no, why do we change to single quote?

2023-09-04 05:27 UTC, fryorcraken approved these changes

2023-09-04 07:07 UTC, merged