fix!: changing exports name from snake casing to camel case
logos-messaging/logos-delivery-js pull request #1934
Opened 2024-03-29 10:48 UTC by varunsh20

## Problem
Some exports are using snake casing within the codebase.

## Solution

Have changed the exports name in core and proto packages to camel case.

## Notes

- Resolves #1933
- Related to https://github.com/waku-org/js-waku/issues/1933

2024-04-01 09:01 UTC, danisharora099 requested changes
some changes I can see:
- [ ] update imports for the changed exports
- [ ] change the PR title to include `!` to convey a breaking change

2024-04-01 11:11 UTC, varunsh20 commented
@danisharora099 changes done. Correct me if I am wrong but I think some exports like waku_filter, waku_store and few others are not used currently. Rest I have changed.

2024-04-09 10:15 UTC, danisharora099 commented
> @danisharora099 changes done. Correct me if I am wrong but I think some exports like waku_filter, waku_store and few others are not used currently. Rest I have changed.

@varunsh20 
Yes. Would suggest at fixing the CI runs which would implicitly take care a lot of smaller things. Will come back for a final review then

2024-04-23 12:44 UTC, danisharora099 commented
Hi @varunsh20 are you still interested in this PR? 
If not, we can close it.

2024-05-30 09:07 UTC, closed without merging